
name: deploy_api

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '**'

env:
  AZURE_FUNCTIONAPP_NAME: 'edportfoliofuncpy'  # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'  # set this to the path to your function app project, defaults to the repository root

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Add your Azure service principal credentials as a secret

      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Set the Python version you are using

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace 'requirements.txt' with the name of your requirements file

      - name: 'Deploy to Azure Functions'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

